version: '3'

services:
  hamachi:
    image: cuongnb14/hamachi
    hostname: hamachi
    container_name: hamachi
    network_mode: "host"
    # restart: always
    privileged: true
    # command: ping fb.com
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
